Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/9"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "12288"
    vb.cpus = 8
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.linked_clone = true
    vb.check_guest_additions = false
  end
end
